[package]
name = "autonomi-service"
version = "0.1.0"
edition = "2021"

[dependencies]
autonomi = "0.3.6"
tokio = { version = "1.43.0", features = ["full"] }
actix-web = "4.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"